title: Example Site
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://jrwesa.github.io/index.html
permalink: pretty

logo: 

favicon_ico: 
